### ISSUE TITLE
User Story #1 - A casual visitor

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/MyPersonalSite#1]
**User story:**
As a casual visitor, I'm interested in learning more about Charles, who he is and what he does.  The site must be easy to navigate though, and have a logical progression.

**Acceptance Criteria:**

- [ ] The website must contain interesting information about Charles.
- [ ] Familiar navigation tools must be used.
- [ ] There must be a logical flow to the pages. 

**Tasks:**

- [ ] Write and present information in a clear and concise way.
- [ ] Use links and navbars.
- [ ] Make sure links and navbars are where you expect to see them.
- [ ] Include a footer.
