### ISSUE TITLE
User Story #2 - A student or potential student

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/MyPersonalSite#2]
**User Story:**
As a student, or potential student of The Code Institute, I'm interested to learn about what the course is, what it teaches you and how much you can learn in a short space of time.  I like the idea of a progression from simple HTML code to more sophisticated tools and techniques.

**Acceptance Criteria:**

- [ ] The site should include a section on CI, the course, and my background in coding (or lack thereof).
- [ ] The information should highlight the current amount of time spent learning so far.
- [ ] The site should develop in a linear way from HTML up to usage of all of the tools taught so far (incl. CSS, Bootstrap, Copilot, VS Code, Font Awesome, Google Fonts).

**Tasks:**

- [ ] Write paragraph on CI and link to their site and this specific course.
- [ ] Write about my journey and how long I've been studying coding for.
- [ ] Use all of the tools, but gradually across the pages.
