### ISSUE TITLE
To Do Checklist

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/MyPersonalSite#8]
Here's the overall checklist which will sit in "In Progress" until the final completion:

- [x] Write user stories
- [x] Write brief for each page
- [ ] Create wireframes for each page
- [x] Create page 1
- [x] Deploy early
- [x] Create page 2
- [ ] Create page 3
- [ ] Test page 3 on different devices
- [ ] Create page 4
- [ ] Create page 5
- [ ] Validate code
- [ ] Write Readme file
